---
- hosts: all
  become: true

  tasks:
    - name: check whether openssh and openssl are installed
      ansible.builtin.apt:
        name: "{{ item }}"
        state: latest
      loop:
        - openssh
        - openssl
      ignore_errors: true

    - name: check whether docker is installed
      ansible.builtin.command: docker --version
      register: docker_installed
      ignore_errors: true

    - name: install docker
      ansible.builtin.apt:
        name: docker.io
        state: latest
      when: docker_installed is failed